name: Unity Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}
          restore-keys: |
            Library-

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4.8.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnityBuild
          path: build
